const iu = require('./lib');

const str = `# Generated by iptables-save v1.8.4 on Wed Aug  9 16:05:47 2023
*filter
:INPUT ACCEPT [3157:285458]
:FORWARD ACCEPT [0:0]
:OUTPUT ACCEPT [5357:3687412]
COMMIT
# Completed on Wed Aug  9 16:05:47 2023
`;

const iptables = new iu.Iptables(str);
iptables.addChain('CLE_INPUT')

iptables.addRuleAtFront('CLE_INPUT', '-A CLE_INPUT -p tcp -m multiport --dports 33333,44444 -j ACCEPT')

iptables.removeChainByName('KSC_IN_PRIVATE_ALLOW')
console.log(iptables.output)