const iu = require('./lib');

const str = `# Generated by iptables-save v1.8.4 on Thu Aug  3 16:16:09 2023
*filter
:INPUT ACCEPT [1289:109905]
:FORWARD ACCEPT [0:0]
:OUTPUT ACCEPT [5833:2154361]
:KSC_IN_PRIVATE_ALLOW - [0:0]
:KSC_IN_PRIVATE_DENY - [0:0]
:KSC_IN_PUBLIC_ALLOW - [0:0]
:KSC_IN_PUBLIC_DENY - [0:0]
:KSC_OUT_PRIVATE_ALLOW - [0:0]
:KSC_OUT_PRIVATE_DENY - [0:0]
:KSC_OUT_PUBLIC_ALLOW - [0:0]
:KSC_OUT_PUBLIC_DENY - [0:0]
:KSC_PRIVATE_INPUT - [0:0]
:KSC_PRIVATE_OUTPUT - [0:0]
:KSC_PUBLIC_INPUT - [0:0]
:KSC_PUBLIC_OUTPUT - [0:0]
-A INPUT -i ens33 -j KSC_PUBLIC_INPUT
-A OUTPUT -o ens33 -j KSC_PUBLIC_OUTPUT
-A KSC_IN_PRIVATE_ALLOW -p tcp -m multiport --sports 7070,17070 -j ACCEPT
-A KSC_IN_PRIVATE_ALLOW -p udp -m multiport --sports 7070,17070 -j ACCEPT
-A KSC_IN_PRIVATE_ALLOW -p icmp -j ACCEPT
-A KSC_IN_PRIVATE_ALLOW -p tcp -m multiport --dports 445,139,3350,3389,22,631,53,24605,8750,7250,8668,25,10080,39901 -j ACCEPT
-A KSC_IN_PRIVATE_ALLOW -p udp -m multiport --dports 137,138,500,4500,5353,49251,33922,53,1701,68,39900 -j ACCEPT
-A KSC_IN_PRIVATE_ALLOW -p tcp -m multiport --sports 80,443,59546 -j ACCEPT
-A KSC_IN_PRIVATE_ALLOW -p udp -m multiport --sports 80,443,59546 -j ACCEPT
-A KSC_IN_PRIVATE_ALLOW -p udp -m multiport --dports 1991 -j ACCEPT
-A KSC_IN_PRIVATE_ALLOW -p tcp -m multiport --dports 27180,27181,27182,27185:27198 -j ACCEPT
-A KSC_IN_PRIVATE_ALLOW -p tcp -m multiport --dports 5900 -j ACCEPT
-A KSC_IN_PRIVATE_ALLOW -p tcp -m multiport --dports 9977 -j ACCEPT
-A KSC_IN_PRIVATE_ALLOW -p udp -m multiport --dports 9977 -j ACCEPT
-A KSC_IN_PRIVATE_ALLOW -p tcp -m multiport --dports 22 -j ACCEPT
-A KSC_IN_PUBLIC_ALLOW -p tcp -m multiport --sports 7070,17070 -j ACCEPT
-A KSC_IN_PUBLIC_ALLOW -p udp -m multiport --sports 7070,17070 -j ACCEPT
-A KSC_IN_PUBLIC_ALLOW -p udp -m multiport --dports 1991 -j ACCEPT
-A KSC_IN_PUBLIC_ALLOW -p tcp -m multiport --dports 27180,27181,27182,27185:27198 -j ACCEPT
-A KSC_IN_PUBLIC_ALLOW -p tcp -m multiport --dports 9977 -j ACCEPT
-A KSC_IN_PUBLIC_ALLOW -p udp -m multiport --dports 9977 -j ACCEPT
-A KSC_IN_PUBLIC_ALLOW -p tcp -m multiport --dports 22 -j ACCEPT
-A KSC_OUT_PRIVATE_ALLOW -p tcp -m multiport --dports 7070,17070 -j ACCEPT
-A KSC_OUT_PRIVATE_ALLOW -p udp -m multiport --dports 7070,17070 -j ACCEPT
-A KSC_OUT_PRIVATE_ALLOW -p icmp -j ACCEPT
-A KSC_OUT_PRIVATE_ALLOW -p tcp -m multiport --sports 445,139,3350,3389,22,631,53,24605,8750,7250,8668,25,10080,39901 -j ACCEPT
-A KSC_OUT_PRIVATE_ALLOW -p udp -m multiport --sports 137,138,500,4500,5353,49251,33922,53,1701,68,39900 -j ACCEPT
-A KSC_OUT_PRIVATE_ALLOW -p tcp -m multiport --dports 80,443,59546 -j ACCEPT
-A KSC_OUT_PRIVATE_ALLOW -p udp -m multiport --dports 80,443,59546 -j ACCEPT
-A KSC_OUT_PRIVATE_ALLOW -p udp -m multiport --sports 1991 -j ACCEPT
-A KSC_OUT_PRIVATE_ALLOW -p tcp -m multiport --sports 27180,27181,27182,27185:27198 -j ACCEPT
-A KSC_OUT_PRIVATE_ALLOW -p tcp -m multiport --sports 5900 -j ACCEPT
-A KSC_OUT_PRIVATE_ALLOW -p tcp -m multiport --sports 9977 -j ACCEPT
-A KSC_OUT_PRIVATE_ALLOW -p udp -m multiport --sports 9977 -j ACCEPT
-A KSC_OUT_PRIVATE_ALLOW -p tcp -m multiport --sports 22 -j ACCEPT
-A KSC_OUT_PUBLIC_ALLOW -p tcp -m multiport --dports 7070,17070 -j ACCEPT
-A KSC_OUT_PUBLIC_ALLOW -p udp -m multiport --dports 7070,17070 -j ACCEPT
-A KSC_OUT_PUBLIC_ALLOW -p udp -m multiport --sports 1991 -j ACCEPT
-A KSC_OUT_PUBLIC_ALLOW -p tcp -m multiport --sports 27180,27181,27182,27185:27198 -j ACCEPT
-A KSC_OUT_PUBLIC_ALLOW -p tcp -m multiport --sports 9977 -j ACCEPT
-A KSC_OUT_PUBLIC_ALLOW -p udp -m multiport --sports 9977 -j ACCEPT
-A KSC_OUT_PUBLIC_ALLOW -p tcp -m multiport --sports 22 -j ACCEPT
-A KSC_PRIVATE_INPUT -j KSC_IN_PRIVATE_DENY
-A KSC_PRIVATE_INPUT -m conntrack --ctstate RELATED,ESTABLISHED,DNAT -j ACCEPT
-A KSC_PRIVATE_INPUT -i lo -j ACCEPT
-A KSC_PRIVATE_INPUT -j KSC_IN_PRIVATE_ALLOW
-A KSC_PRIVATE_INPUT -m conntrack --ctstate INVALID -j DROP
-A KSC_PRIVATE_INPUT -j REJECT --reject-with icmp-host-prohibited
-A KSC_PRIVATE_OUTPUT -j KSC_OUT_PRIVATE_DENY
-A KSC_PRIVATE_OUTPUT -j KSC_OUT_PRIVATE_ALLOW
-A KSC_PUBLIC_INPUT -j KSC_IN_PUBLIC_DENY
-A KSC_PUBLIC_INPUT -m conntrack --ctstate RELATED,ESTABLISHED,DNAT -j ACCEPT
-A KSC_PUBLIC_INPUT -i lo -j ACCEPT
-A KSC_PUBLIC_INPUT -j KSC_IN_PUBLIC_ALLOW
-A KSC_PUBLIC_INPUT -m conntrack --ctstate INVALID -j DROP
-A KSC_PUBLIC_INPUT -j REJECT --reject-with icmp-host-prohibited
-A KSC_PUBLIC_OUTPUT -j KSC_OUT_PUBLIC_DENY
-A KSC_PUBLIC_OUTPUT -j KSC_OUT_PUBLIC_ALLOW
COMMIT
# Completed on Thu Aug  3 16:16:09 2023
`;

const iptables = new iu.Iptables(str);
iptables.addChain('CLE_INPUT')

iptables.addRuleAtFront('CLE_INPUT', '-A CLE_INPUT -p tcp -m multiport --dports 33333,44444 -j ACCEPT')

iptables.removeChainByName('KSC_IN_PRIVATE_ALLOW')
console.log(iptables.output)